- graph/tree/binarySearchTree/binarySearch.cpp
i have added a program of binary search tree #4
> Added BinarySearchtree

- README.md
> Updated Readme! #16

- maths/prime number tricks/List all primes.cpp
All primes are of form 6*k +- 1, instead of doing primality test on all numbers, the programmer can improve the efficiency of his code by only performing the test on a precomputed list which includes all the primes (with some garbage) minus most of the composite numbers.
> PR for Hacktoberfest: Added Program to find all primes without checking all numbers

- README.md
- graph/FloydWarshall.cpp
> added Floyd Warshall

- README.md
> Updated little mistakes in the readme.md

- algo.py
> Cocktail sort 

- Searching Algorithms/Jump_Search.cpp
Like Binary Search, Jump Search is a searching algorithm for sorted arrays. The basic idea is to check fewer elements (than linear search) by jumping ahead by fixed steps or skipping some elements in place of searching all elements.
#2
> Jump Search algorithm implementation in C++.

- divide_and_conquer/maximum_sub_array.cpp
C++ code for finding the largest sub array with the maximum sum using divide and conquer algorithm.
Time Complexity: O(nlgn)
> maximum sub array problem using divide and conquer

- Python implementation DataStructures/Queue.py
- Searching Algorithms/MEDIAN_SEARCH.cpp
Median Search Algorithm .
Useful for finding the kth smallest or the kth Largest Element.
Complexity - O(n)
> MedianSearch #2

- README.md
> Tiny update of README.md #16

- Python implementation DataStructures/Queue.py
Python based implementation of Queue
>  Queue.py#20

- Python implementation DataStructures/stack.py
Implementation of stack in Python
> Create stack.py #20

- Searching Algorithms/Interpolation_search.cpp
- tree/Fenwick_tree.cpp
> Added Interpolation search

- dp/coinchange.cpp
- dp/lcs.cpp
Dynamic Programming Problems Added-
1) Coin Change Problem
2) Longest Common Subsequence Problem
> Basic DP problems added

- Searching Algorithms/Binary_Search.cpp
As per this issue, https://github.com/srbcheema1/Algo_Ds/issues/2. Adding the Binary Search Algorithm in CPP.
> Adding Binary Search in cpp

- tree/trie.cpp
> Add Trie #2

- segment_tree/segment_tree.cpp
segment_tree.cpp can create update and query the segment tree as u wish.
Looking forward to more such pull requests.
> Added a new section of segment tree.

- graph/dijakstra/Dijkstra.java
Dijkstra algorithm in java with file I/O
> Dijkstra algo in java

- divide_and_conquer/strassen.cpp
- dp/mcm.cpp
Divide and Conquer Approach for Stressen's Multiplication 
DP approach for finding optimum cost in Matrix Chain Multiplicationn
> Stressens Multiplication and Matrix Chain Multiplication

- Searching Algorithms/ternarySearch.cpp
>  Added Ternaray Search C++ code

- Searching Algorithms/bst.py
> add bst.py

- graph/bfs_dfs/ques/graph_connected_components.cpp
> added Graph algo for connected components

- maths/prime/sieveOferatosthenes.cpp
> Code for implementing sieve of eratosthenes

- stack/largestRectangleHistogram.cpp
Resolving #3 .
Finding the largest area Rectangle in a histogram using stacks.
> Stack implementation for largest area rectangle in histogram

- dp/editDistance.cpp
Resolving #2 .
Added Code for EditDistance in Cpp using Dynamic Programming
> Added Code for EditDistance Problem

- Sorting Algorithms/BubbleSort.py
> Created BubbleSort.py

- Python implementation DataStructures/dfs.py
Resolving #20 
Python Implementation for Depth First Search
> Added DFS code in python

- STACK_with_Application/Evaluating Postfix Expression.c
- STACK_with_Application/Infix to Postfix.c
- STACK_with_Application/balance parenthesis.cpp
- STACK_with_Application/stack_and_its_implementation.c
> Stack - Implementation and Application

- Searching Algorithms/Binary_Search.cpp
- Searching Algorithms/Interpolation Search
- Searching Algorithms/Interpolation_search.cpp
- Searching Algorithms/Jump_Search.cpp
- Searching Algorithms/bst.py
- Searching Algorithms/ternarySearch.cpp
Resolving #63 .
Added Time Complexities for all sorting algorithms.
> added time complexity for each

- dp/0-1knapsack.cpp
- dp/eggdropping.cpp
- dp/kadane.cpp
- dp/lis.cpp
Basic algos like LIS, Kadane's, 0-1 knapsack and egg dropping puzzle have been added.
> Basic DP algorithms

- Backtrack/Rat_Maze_Recurssion_Backtracking.c
- Backtrack/m-coloring-problem.py
- Backtrack/nqueen_allsol.py
> Adding Backtracking Algorithms

- String_algo/KMP.cpp
- String_algo/SUFFIX-ARRAY.cpp
- String_algo/z_algorithm.cpp
Added section for string_algorithms and implemented three algos
> Added section for string_algorithms

- Sorting Algorithms/bubblesort.js
> added bubblesort in javascript

- BST/checkbst
this program checks whether the binary tree entered is binary search tree or not.
> created a checkbst cpp file

- Backtrack/permutations_of_string.cpp
Issue #72 @srbcheema1 Please review.
> Added Permutations of String problem in Backtrack Section

- graph/bfs_dfs/dfs/DFS.java
> DFS algorithm in Java

- Data Structures/C:C++/Graph/bfs_dfs/bfs/bfs.Py
Breadth First Traversal or BFS for a Graph.
Time Complexity: O(V+E) where V is number of vertices in the graph and E is number of edges in the graph.
> Added bfs.py file

- CONTRIBUTION.md
This pull request relates to Issue #89.
> Added capitalisation, punctuation and fixed typos in CONTRIBUTION.md

- CONTRIBUTION.md
Preview link: <a href="https://github.com/harshit98/Algo_Ds/blob/master/CONTRIBUTION.md">here</a>
> Addresses #89: Update CONTRIBUTING.md

- graph/bfs_dfs/dfs/DFS.cpp
My implementation of dfs in c++.
> Add a DFS in c++

- CONTRIBUTION.md
Improved grammar, spelling, and added clarity to contribution guidelines.
> Fixes Issue #89: Improved contribution guidelines.

- Backtrack/NQueen.cpp
N-Queen implementation in C++ Referencing Issue #72 
@srbcheema1 Please review!
> N-Queen in c++ added

- Dynamic Programing/Edit Distance.Py
- Dynamic Programing/Knapsack.py
- Dynamic Programing/Memoized Cut Rod.Py
- Dynamic Programing/Word_Wrap.Py
> Adding Dynamic Programming Problems

- Data Structures/C:C++/Linked List/stack_Linked_List.c
I updated the stackLinkedList.c file because it was missing many things.
This is my first pull request too.
Please tell me if i did something wrong
> Updated satckLinkedList c file

- Data Structures/C:C++/Stack/Balanced_Brackets.cpp
Code written in C++ with proper indentation to check whether a string is Bracket Balanced or not.
> In connection with #Issue 3  Checks whether the Brackets(Parenthesis) are Balanced or not. 

- genome_sort.py
> Genome Sorting in Python

- Mathematical Challenges/python/pernicious_prime/pernicious.py
The problem is to identify whether a given input number (any positive number other than 1 and 2 ) is pernicious number (can also be said as prime) or not . 
Problem is coded in python language and tested across all possible edge cases.
> Added a math problem of pernicious prime in python

- dfs.cpp
- square_root_decomposition
- travelling_salesman_problem
Sqrt (or Square Root) Decomposition Technique is one of the most common query optimization technique used by competitive programmers. This technique helps us to reduce Time Complexity by a factor of sqrt(n).
The key concept of this technique is to decompose given array into small chunks specifically of size sqrt(n).
> square_root_decomposition

- Sorting Algorithms/Python/mergesort.py
Full code of merge sort in python3 with an example. Also provided the time and space complexity.
> merge sort code in python3

- BST/lca.cpp
In binary search trees, finding LCA between 2 nodes is also an interesting problem to solve.
So I've added the problem in BST section.
> Added Lowest common ancestor in BST

- Segment Trees/ADA/README.md
- Segment Trees/ADA/segmentree.adb
An ADA language implementation of Segment Tree with a brief explanation
> Implementation of segment tree in ADA
